name: Generate terminal session
uses: lowlighter/metrics@latest
on:
  push:
    branches: main
  workflow_dispatch:
with:
  template: terminal
  filename: metrics.terminal.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: header, metadata
